[package]
name = "rust_baby"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "0.10.0"
rand = "0.8.5"

[[bin]]
name = "rust_baby"
path = "src/main.rs"
